// VDDLoader.idl : IDL source for VDDLoader.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (VDDLoader.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(9F2F8D7B-DA82-11D4-9C30-00A024112F81),
	version(1.0),
	helpstring("VDDLoader 1.0 Implementation Type Library")
]
library VDDLOADERLib
{
	importlib("../Interfaces/IVDMModule.tlb");
	importlib("../Interfaces/IVDMServices.tlb");

	[
		uuid(507AC2BE-DC6F-11D4-9C37-00A024112F81),
		helpstring("VDMServices Class")
	]
	coclass VDMServices
	{
		interface IVDMBasicModule;
		interface IVDMBaseServices;
	};
};
