// EmuAdLib.idl : IDL source for EmuAdLib.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (EmuAdLib.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(1E287541-4121-11D5-9D36-00A024112F81),
	version(1.0),
	helpstring("EmuAdLib 1.0 Type Library")
]
library EMUADLIBLib
{
	import "IVDMModule.idl";
	import "IVDMHandlers.idl";

	[
		uuid(18D98B72-41AA-11D5-9D37-00A024112F81),
		helpstring("AdLibCtl Class")
	]
	coclass AdLibCtl
	{
		[default] interface IVDMBasicModule;
		interface IIOHandler;
	};
};
