// DiskWriter.idl : IDL source for DiskWriter.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DiskWriter.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(86337441-0C1E-11D5-9CD3-00A024112F81),
	version(1.0),
	helpstring("DiskWriter 1.0 Type Library")
]
library DISKWRITERLib
{
	import "IVDMModule.idl";
	import "IWave.idl";

	[
		uuid(8633744F-0C1E-11D5-9CD3-00A024112F81),
		helpstring("WaveOut Class")
	]
	coclass WaveOut
	{
		[default] interface IVDMBasicModule;
		interface IWaveDataConsumer;
	};
};
