// MIDIToolkit.idl : IDL source for MIDIToolkit.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MIDIToolkit.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(2C220FD1-0125-11D5-9C68-00A024112F81),
	version(1.0),
	helpstring("MIDIToolkit 1.0 Type Library")
]
library MIDITOOLKITLib
{
	import "IVDMModule.idl";
	import "IMIDI.idl";

	[
		uuid(2C220FDF-0125-11D5-9C68-00A024112F81),
		helpstring("MIDIMapper Class")
	]
	coclass MIDIMapper
	{
		[default] interface IVDMBasicModule;
		interface IMIDIEventHandler;
	};
	[
		uuid(2C220FE3-0125-11D5-9C68-00A024112F81),
		helpstring("MIDISplitter Class")
	]
	coclass MIDISplitter
	{
		[default] interface IVDMBasicModule;
		interface IMIDIEventHandler;
	};
	[
		uuid(816E3CC2-A0AF-11D5-9D8C-00A024112F81),
		helpstring("MIDIDelay Class")
	]
	coclass MIDIDelay
	{
		[default] interface IVDMBasicModule;
		interface IMIDIEventHandler;
	};
};
