// MIDIToolkit.idl : IDL source for MIDIToolkit.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MIDIToolkit.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(2C220FE0-0125-11D5-9C68-00A024112F81),
	
		helpstring("IMIDIMapper Interface"),
		pointer_default(unique)
	]
	interface IMIDIMapper : IUnknown
	{
	};
	[
		object,
		uuid(2C220FE2-0125-11D5-9C68-00A024112F81),
	
		helpstring("IMIDISplitter Interface"),
		pointer_default(unique)
	]
	interface IMIDISplitter : IUnknown
	{
	};

[
	uuid(2C220FD1-0125-11D5-9C68-00A024112F81),
	version(1.0),
	helpstring("MIDIToolkit 1.0 Type Library")
]
library MIDITOOLKITLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(2C220FDF-0125-11D5-9C68-00A024112F81),
		helpstring("MIDIMapper Class")
	]
	coclass MIDIMapper
	{
		[default] interface IMIDIMapper;
	};
	[
		uuid(2C220FE3-0125-11D5-9C68-00A024112F81),
		helpstring("MIDISplitter Class")
	]
	coclass MIDISplitter
	{
		[default] interface IMIDISplitter;
	};
};
