import "oaidl.idl";

[
	object,
	uuid(F09AFF00-FD87-11d4-9C63-00A024112F81),
	helpstring(""),
	pointer_default(unique)
]
interface IMIDIEventHandler : IUnknown
{
	[ helpstring("Handles a simple MIDI message") ]
	HRESULT HandleEvent(
		[in] LONGLONG usDelta,              // timestamp (microseconds elapsed, counted from a fixed reference point)
		[in] BYTE status,                   // the MIDI status byte
		[in] BYTE data1,                    // the first byte of MIDI data (when needed)
		[in] BYTE data2,                    // the second byte of MIDI data (when needed)
		[in] BYTE length );                 // number of data bytes in the message (0 to 2)

	[ helpstring("Handles a MIDI System Exclusive message") ]
	HRESULT HandleSysEx(
		[in] LONGLONG usDelta,              // timestamp (microseconds elapsed, counted from a fixed reference point)
		[in, size_is(length)] BYTE data[],  // system exclusive data bytes
		[in] LONG length );                 // number of data bytes in the system exclusive message

	[ helpstring("Handles a MIDI Realtime message") ]
	HRESULT HandleRealTime(
		[in] LONGLONG usDelta,              // timestamp (microseconds elapsed, counted from a fixed reference point)
		[in] BYTE data );                   // realtime message
};



/////////////////////////////////////////////////////////////////////////////



[
	uuid(14C106C0-FD88-11d4-9C63-00A024112F81),
	version(1.0),
	helpstring("MIDI 1.0 Definition Type Library")
]
library IMIDILib
{
	interface IMIDIEventHandler;
};
