import "oaidl.idl";

import "IVDMQuery.idl";


[
	object,
	uuid(93F77400-E4EB-11d4-9C44-00A024112F81),
	helpstring("Base VDM module: initialization & destruction"),
	pointer_default(unique)
]
interface IVDMBasicModule : IUnknown
{
	/******************************************************
	*	Initialization & destruction
	******************************************************/

	[ helpstring("Initialize") ]
	HRESULT Init(
		[in] IUnknown * configuration );

	[ helpstring("Destroy") ]
	HRESULT Destroy( );
};



/////////////////////////////////////////////////////////////////////////////



[
	uuid(4321E500-E4F4-11d4-9C44-00A024112F81),
	version(1.0),
	helpstring("VDMModule 1.0 Definition Type Library")
]
library IVDMMODULELib
{
	interface IVDMBasicModule;
};
