// MIDIIndicator.idl : IDL source for MIDIIndicator.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MIDIIndicator.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(C7A8FCA8-FEA8-11D4-9C65-00A024112F81),
	version(1.0),
	helpstring("MIDIIndicator 1.0 Type Library")
]
library MIDIINDICATORLib
{
	import "IVDMModule.idl";
	import "IMIDI.idl";

	[
		uuid(C7A8FCB6-FEA8-11D4-9C65-00A024112F81),
		helpstring("ActivityLights Class")
	]
	coclass ActivityLights
	{
		[default] interface IVDMBasicModule;
		interface IMIDIEventHandler;
	};
};
