// MIDIDevice.idl : IDL source for MIDIDevice.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MIDIDevice.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(F3285833-FDE7-11D4-9C64-00A024112F81),
	version(1.0),
	helpstring("MIDIDevice 1.0 Type Library")
]
library MIDIDEVICELib
{
	import "IVDMModule.idl";
	import "IMIDI.idl";

	[
		uuid(F3285843-FDE7-11D4-9C64-00A024112F81),
		helpstring("MIDIOut Class")
	]
	coclass MIDIOut
	{
		[default] interface IVDMBasicModule;
		interface IMIDIEventHandler;
	};
};
