import "oaidl.idl";

[
	object,
	uuid(72F0DB50-7DA0-11d5-9D67-00A024112F81),
	helpstring(""),
	pointer_default(unique)
]
interface IAddressable : IUnknown
{
	[ helpstring("Handles a byte read") ]
	HRESULT HandleByteRead(
		[in] ULONG address,                 // address the read operation is performed on
		[out] BYTE * data );                // data to be returned to the 16-bit application

	[ helpstring("Handles a word read") ]
	HRESULT HandleWordRead(
		[in] ULONG address,                 // address the read operation is performed on
		[out] WORD * data );                // data to be returned to the 16-bit application

	[ helpstring("Handles a byte write") ]
	HRESULT HandleByteWrite(
		[in] ULONG address,                 // address the write operation is performed on
		[in] BYTE data );                   // data from the 16-bit application

	[ helpstring("Handles a word write") ]
	HRESULT HandleWordWrite(
		[in] ULONG address,                 // address the write operation is performed on
		[in] WORD data );                   // data from the 16-bit application
};



/////////////////////////////////////////////////////////////////////////////



[
	uuid(8B83F240-7DA0-11d5-9D67-00A024112F81),
	version(1.0),
	helpstring("IOxxx 1.0 Definition Type Library")
]
library IAddressableLib
{
	interface IAddressable;
};
