// WaveDevice.idl : IDL source for WaveDevice.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (WaveDevice.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(088488B3-0684-11D5-9C73-00A024112F81),
	version(1.0),
	helpstring("WaveDevice 1.0 Type Library")
]
library WAVEDEVICELib
{
	import "IVDMModule.idl";
	import "IWave.idl";

	[
		uuid(088488C1-0684-11D5-9C73-00A024112F81),
		helpstring("WaveOut Class")
	]
	coclass WaveOut
	{
		[default] interface IVDMBasicModule;
		interface IWaveDataConsumer;
	};
};
