// EmuSBCompat.idl : IDL source for EmuSBCompat.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (EmuSBCompat.tlb) and marshalling code.

import "oaidl.idl";

[
	uuid(93F176E7-0362-11D5-9C6D-00A024112F81),
	version(1.0),
	helpstring("EmuSBCompat 1.0 Type Library")
]
library EMUSBCOMPATLib
{
	import "IVDMModule.idl";
	import "IVDMHandlers.idl";
	import "IDMAHandlers.idl";

	[
		uuid(93F176F5-0362-11D5-9C6D-00A024112F81),
		helpstring("SBCompatCtl Class")
	]
	coclass SBCompatCtl
	{
		[default] interface IVDMBasicModule;
		interface IIOHandler;
		interface IDMAHandler;
	};
};
